### ISSUE TITLE
Unable to load library 'server.dylib'

### ISSUE THREAD

**Issue by AlecHaring** [sleeyax/burp-awesome-tls#16]
After loading the extension in Burp, the following error is shown in stdout:
```
dlopen(libserver.dylib.dylib, 0x0009): tried: 'libserver.dylib.dylib' (relative path not allowed in hardened program), '/usr/lib/libserver.dylib.dylib' (no such file)
dlopen(libserver.dylib.dylib, 0x0009): tried: 'libserver.dylib.dylib' (relative path not allowed in hardened program), '/usr/lib/libserver.dylib.dylib' (no such file)
Native library (darwin-x86-64/libserver.dylib.dylib) not found in resource path ([file:/var/folders/hn/_pcv7pl154bbns24yhwjt05c0000gn/T/burp10831821168041598492.tmp/2])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:622)
	at com.sun.jna.Native.load(Native.java:596)
	at burp.ServerLibrary.<clinit>(ServerLibrary.java:8)
	at burp.BurpExtender.lambda$registerExtenderCallbacks$0(BurpExtender.java:36)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libserver.dylib.dylib, 0x0009): tried: 'libserver.dylib.dylib' (relative path not allowed in hardened program), '/usr/lib/libserver.dylib.dylib' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 7 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libserver.dylib.dylib, 0x0009): tried: 'libserver.dylib.dylib' (relative path not allowed in hardened program), '/usr/lib/libserver.dylib.dylib' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 7 more
	Suppressed: java.io.IOException: Native library (darwin-x86-64/libserver.dylib.dylib) not found in resource path ([file:/var/folders/hn/_pcv7pl154bbns24yhwjt05c0000gn/T/burp10831821168041598492.tmp/2])
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 7 more
```

- OS: macOS 12.6 (Intel)
- Burp version: v2022.8.4 CE
- Using [Burp-Awesome-TLS-macos-amd64.jar](https://github.com/sleeyax/burp-awesome-tls/releases/download/v0.0.2-rc.2/Burp-Awesome-TLS-macos-amd64.jar) from release [v0.0.2-rc.2](https://github.com/sleeyax/burp-awesome-tls/releases/tag/v0.0.2-rc.2)

**Comment by AlecHaring** [comment]
Seems like the problem is that it's looking for `libserver.dylib.dylib`, but unzipping the `2` file in `burp10831821168041598492.tmp/` reveals the file's name is just `server.dylib`

**Comment by sleeyax** [comment]
Odd, I don't immediately see why it would look for  `libserver.dylib.dylib` . It should be just  `server.dylib` :thinking:

**Comment by sleeyax** [comment]
I checked out the JNA (Java Native Access) source code and according to this code snippet it seems like only on MacOS native libraries are expected to start with `lib`:

https://github.com/java-native-access/jna/blob/87f32b5a1e818533004a41f3071e55e0aa3a39b5/src/com/sun/jna/NativeLibrary.java#L761-L801

```java
    static String mapSharedLibraryName(String libName) {
        if (Platform.isMac()) {
            if (libName.startsWith("lib")
                && (libName.endsWith(".dylib")
                    || libName.endsWith(".jnilib"))) {
                return libName;
            }
            String name = System.mapLibraryName(libName);
            // On MacOSX, System.mapLibraryName() returns the .jnilib extension
            // (the suffix for JNI libraries); ordinarily shared libraries have
            // a .dylib suffix
            if (name.endsWith(".jnilib")) {
                return name.substring(0, name.lastIndexOf(".jnilib")) + ".dylib";
            }
            return name;
        }
        else if (Platform.isLinux() || Platform.isFreeBSD()) {
            if (isVersionedName(libName) || libName.endsWith(".so")) {
                // A specific version was requested - use as is for search
                return libName;
            }
        }
        else if (Platform.isAIX()) {    // can be libx.a, libx.a(shr.o), libx.so
            if (isVersionedName(libName) || libName.endsWith(".so") || libName.startsWith("lib") || libName.endsWith(".a")) {
                // A specific version was requested - use as is for search
                return libName;
            }
        }
        else if (Platform.isWindows()) {
            if (libName.endsWith(".drv") || libName.endsWith(".dll") || libName.endsWith(".ocx")) {
                return libName;
            }
        }


        String mappedName = System.mapLibraryName(libName);
        if(Platform.isAIX() && mappedName.endsWith(".so")) {
            return mappedName.replaceAll(".so$", ".a");
        } else {
            return mappedName;
        }
    }
```

I'll need to update the build script to support this.

**Comment by AlecHaring** [comment]
Huh, very interesting. And that code snippet also explains why it adds a 2nd `.dylib` to the end of the lib name. So adding `lib` to the beginning of the name would fix that as well :)

**Comment by sleeyax** [comment]
Should be fixed in the latest build (Github Action is still running at the time of writing, check releases soon).

**Comment by AlecHaring** [comment]
Yep, that fixed it. Thanks!
