### ISSUE TITLE
java.lang.NumberFormatException: Cannot parse null string

### ISSUE THREAD

**Issue by teamtopkarl** [sleeyax/burp-awesome-tls#67]
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:624)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at burp.Settings.getHttpTimeout(Settings.java:107)
	at burp.SettingsTab.<init>(SettingsTab.java:65)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:36)
	at burp.Zcpy.ZM(Unknown Source)
	at burp.Zlor.ZC(Unknown Source)
	at burp.Zlob.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by fleabane1** [comment]
me too

**Comment by sleeyax** [comment]
See #15.
