### ISSUE TITLE
arm64 java21 burp2024

### ISSUE THREAD

**Issue by gusechuisheng** [sleeyax/burp-awesome-tls#82]
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:550)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at burp.Settings.getTimeout(Settings.java:52)
	at burp.SettingsTab.<init>(SettingsTab.java:38)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33)
	at burp.Zm9d.ZN(Unknown Source)
	at burp.Zu1s.Zg(Unknown Source)
	at burp.Zu11.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by swapgroax** [comment]
Use burpsuite 2023 //2short.
