### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CharlieNeva2Late777** [sleeyax/burp-awesome-tls#84]
I would like to know if there is documentation because it's difficult to understand the directives! Thank you

**Comment by sleeyax** [comment]
There's the readme. What else is difficult to understand?

**Comment by sleeyax** [comment]
And there are also hints when you hover over the input fields with your mouse.

**Comment by CharlieNeva2Late777** [comment]
> And there are also hints when you hover over the input fields with your mouse.

That's weird because on mac when I get the amd awesome TLS extension I get this error when I load it:

```
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:624)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at burp.Settings.getHttpTimeout(Settings.java:107)
	at burp.SettingsTab.<init>(SettingsTab.java:65)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:36)
	at burp.Zvx1.Zk(Unknown Source)
	at burp.Zfb5.Zf(Unknown Source)
	at burp.Zfbe.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
